import { useEffect, useRef, useState } from "react";
import type Portal from "@arcgis/core/portal/Portal.js";
import type WebMap from "@arcgis/core/WebMap.js";
import AssistantPanel from "./AssistantPanel";
import MapCanvas from "./MapCanvas";
import { queryWebMaps, signIn, signOut, type CatalogItem, type SignedInUser } from "./arcgis";

const clientId = import.meta.env.VITE_ARCGIS_CLIENT_ID as string | undefined;
export default function App() {
  const [portal, setPortal] = useState<Portal | null>(null); const [user, setUser] = useState<SignedInUser | null>(null); const [maps, setMaps] = useState<CatalogItem[]>([]); const [selected, setSelected] = useState<CatalogItem | null>(null); const [scope, setScope] = useState<"mine" | "organization">("mine"); const [search, setSearch] = useState(""); const [message, setMessage] = useState("Sign in to choose a map."); const map = useRef<WebMap | null>(null);
  useEffect(() => { if (portal) queryWebMaps(portal, scope, search).then(setMaps).catch((error: Error) => setMessage(error.message)); }, [portal, scope, search]);
  if (!clientId) return <main className="app-shell"><section className="panel"><p className="eyebrow">ARCGIS ONLINE</p><h1>Atlas Desk</h1><p>Add <code>VITE_ARCGIS_CLIENT_ID</code> to <code>.env.local</code>.</p></section></main>;
  if (!portal || !user) return <main className="app-shell"><section className="panel"><p className="eyebrow">ARCGIS ONLINE</p><h1>Atlas Desk</h1><p>Open a 2D web map, explore it with AI, and add reversible session layers.</p><button className="primary" onClick={() => signIn(clientId).then(({ portal: next, user: account }) => { setPortal(next); setUser(account); setMessage("Choose a map to begin."); }).catch((error: Error) => setMessage(error.message))}>Sign in to ArcGIS Online</button><small>{message}</small></section></main>;
  return <main className="workspace"><header><strong>Atlas Desk</strong><span>{user.fullName}</span><button onClick={() => { signOut(); setPortal(null); setUser(null); setSelected(null); }}>Sign out</button></header>{!selected ? <section className="catalogue"><p className="eyebrow">MAP CATALOGUE</p><h1>Choose a 2D web map</h1><div className="controls"><button className={scope === "mine" ? "active" : ""} onClick={() => setScope("mine")}>My maps</button><button className={scope === "organization" ? "active" : ""} onClick={() => setScope("organization")}>Organization maps</button><input aria-label="Search maps" placeholder="Filter by title" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="map-list">{maps.map((item) => <button className="map-row" key={item.id} onClick={() => { setSelected(item); setMessage(`Loading ${item.title}.`); }}><strong>{item.title}</strong><span>{item.snippet}</span><small>Owner: {item.owner}</small></button>)}</div></section> : <section className="workspace-grid"><div className="map-region"><MapCanvas itemId={selected.id} onMap={(value) => { map.current = value; }} /><div className="map-caption"><span>{selected.title}</span><button onClick={() => setSelected(null)}>Switch map</button></div></div><aside><div className="readiness"><strong>Assistant readiness</strong><p>Data exploration requires embeddings prepared in ArcGIS Online item settings. Session layers are not saved or guaranteed to be embedded.</p></div><AssistantPanel key={selected.id} portal={portal} title={selected.title} getMap={() => map.current} onAdded={setMessage} /></aside></section>}<footer>{message}</footer></main>;
}